# Generated by Django 6.0.3 on 2026-07-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('sample', 'Synthetic sample data'), ('upload', 'Uploaded JSON file'), ('telegram', 'Live Telegram scrape')], max_length=20)),
                ('source_label', models.CharField(blank=True, max_length=255)),
                ('accounts_analyzed', models.IntegerField(default=0)),
                ('flagged_accounts', models.IntegerField(default=0)),
                ('model_stages', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='LinkedCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_handle', models.CharField(max_length=255)),
                ('account_ids', models.JSONField(default=list)),
                ('scan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='scanner.scanrun')),
            ],
        ),
        migrations.CreateModel(
            name='IngestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=10)),
                ('source', models.CharField(choices=[('sample', 'Synthetic sample data'), ('upload', 'Uploaded JSON file'), ('telegram', 'Live Telegram scrape')], max_length=20)),
                ('targets', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('result_scan_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='scanner.scanrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=30)),
                ('handle', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('is_probable_bot', models.BooleanField(default=False)),
                ('risk_score', models.FloatField()),
                ('risk_band', models.CharField(max_length=10)),
                ('flagged_message_count', models.IntegerField(default=0)),
                ('total_messages_seen', models.IntegerField(default=0)),
                ('features', models.JSONField(default=dict)),
                ('evidence_sample', models.JSONField(default=list)),
                ('message_verdicts', models.JSONField(default=list)),
                ('scan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='scanner.scanrun')),
            ],
            options={
                'ordering': ['-risk_score'],
                'indexes': [models.Index(fields=['scan_run', 'risk_band'], name='scanner_acc_scan_ru_65fb84_idx'), models.Index(fields=['scan_run', 'platform'], name='scanner_acc_scan_ru_c33ff8_idx')],
            },
        ),
    ]
