# Generated by Django 6.0.3 on 2026-07-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrecord',
            name='extracted_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High')], max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('dismissed', 'Dismissed')], default='new', max_length=15)),
                ('message', models.TextField()),
                ('platform', models.CharField(blank=True, max_length=30)),
                ('handle', models.CharField(blank=True, max_length=255)),
                ('risk_score', models.FloatField(default=0.0)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='scanner.accountrecord')),
                ('scan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='scanner.scanrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
