# Generated by Django 6.0.3 on 2026-07-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_accountrecord_extracted_metadata_alert'),
        ('scanner', '0002_add_alert_and_extracted_metadata'),
    ]

    operations = [
    ]
